---
title: "Tweets Data"
output: html_document
---

```{r, echo = FALSE}

library(quanteda)
library(readr)
library(dplyr)
library(knitr)
library(RcmdrMisc)

data <- read.csv("tmls.csv")

data1 <- mutate(data, date = as.POSIXct(as.numeric(data$created_at), origin = '1970-01-01', tz = 'GMT')) %>% subset(select = -c(status_id, urls_url, reply_count, created_at, quote_count))

corp <- corpus(data1)

tokens <- tokens(
  corp,
  what = "fasterword",
  remove_punct = TRUE,
  remove_symbols = TRUE,
  remove_numbers = FALSE,
  remove_url = TRUE,
  remove_separators = TRUE,
  split_hyphens = TRUE)

dfm <- dfm(corp, remove = stopwords("english"), stem = TRUE, remove_punct = TRUE, remove_numbers = TRUE, remove_symbols = TRUE, split_hyphens = TRUE) 
```

```{r}
#this is just a super quick draft of a dictionary, not even split pro or con
guns_dic <- dictionary(list(Guns = c('regulation', 
                                         'safety', 'mass shooting', 
                                      'school shooting','arms regulation', 'background check', 'second amendment','take away', 'AR 15', 'security', 'firearms', 'rifle', 'militia', 'guns', 'weapons', 'handgun', 'shooting')))

dfm3 <- dfm(dfm, group = dfm$screen_name)
View(dfm3[1:10,1:50])

dfm2 <- dfm(dfm, dictionary = guns_dic, group = data$screen_name)
```

